
path: C:/Users/carlo/OneDrive/backups/Documentos2/Notebooks/Estudo_Yolo  # dataset root dir
train: MiteHunter.v1i.yolov8/train  # train images (relative to 'path').
val: MiteHunter.v1i.yolov8/valid  # val images (relative to 'path')



# Classes
names:
  0: Californicus
  1: Macropilis
  2: Rajado