# Generated by Django 5.0.4 on 2024-04-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0002_formfile_remove_uploadfieldform_form_ptr_delete_form_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfile',
            name='cultivo_id',
            field=models.IntegerField(default=0),
        ),
    ]
